version: "3.9"

services:
  postgres:
    image: postgres:14.8-alpine
    environment:
      POSTGRES_DB: "news_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  parser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app